### Task 1: Arrays, Statistics and Indexing

In [5]:
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
array_A = np.random.randint(1,101, size=100)
print(f"Array: {array_A}\n\n")

print(f"Min: {np.min(array_A)}")
print(f"Max: {np.max(array_A)}")
print(f"Median: {np.median(array_A)}")
print(f"Mean: {np.mean(array_A):.2f}")
print(f"Std Dev: {np.std(array_A):.2f}")

array_B = np.arange(100)

zeros_arr = np.zeros((3,3))
ones_arr = np.ones((2,4), dtype=np.float64)
print(f"\nZeros Array Shape: {zeros_arr.shape}, Data Type: {zeros_arr.dtype}")
print(zeros_arr)
print(f"Ones Array Shape: {ones_arr.shape}, Data Type: {ones_arr.dtype}")
print(ones_arr)

linespace_arr = np.linspace(0,10,num=5)
print(f"\nLinspace Array: {linespace_arr}")

Array: [ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22  53   2  88
  30  38   2  64  60  21  33  76  58  22  89  49  91  59  42  92  60  80
  15  62  62  47  62  51  55  64   3  51   7  21  73  39  18   4  89  60
  14   9  90  53   2  84  92  60  71  44   8  47  35  78  81  36  50   4
   2   6  54   4  54  93  63  18  90  44  34  74  62 100  14  95  48  15
  72  78  87  62  40  85  80  82  53  24]


Min: 2
Max: 100
Median: 54.0
Mean: 51.54
Std Dev: 29.28

Zeros Array Shape: (3, 3), Data Type: float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array Shape: (2, 4), Data Type: float64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Linspace Array: [ 0.   2.5  5.   7.5 10. ]


In [7]:
arr_2d = np.arange(1,13).reshape(3,4)
arr_3d = np.arange(1,25).reshape(2,3,4)

print(f"\n2D Array Shape: {arr_2d.shape}, Dimensions (ndim): {arr_2d.ndim}")
print(f"2D Specific Element [1, 2]: {arr_2d[1, 2]}")  # Row index 1, Col index 2 -> 7
print(f"2D Row 0: {arr_2d[0, :]}")
print(f"2D Column 1: {arr_2d[:, 1]}")
print(f"2D Sub-matrix Slicing:\n{arr_2d[0:2, 1:3]}")
print(f"\n3D Array Shape: {arr_3d.shape}, Dimensions (ndim): {arr_3d.ndim}")

reshaped_matrix = array_A.reshape((10,10))
flattened_array = reshaped_matrix.flatten()

print(f"\nReshaped Matrix Shape: {reshaped_matrix.shape}")
print(f"Flattened Array Shape: {flattened_array.shape}")


2D Array Shape: (3, 4), Dimensions (ndim): 2
2D Specific Element [1, 2]: 7
2D Row 0: [1 2 3 4]
2D Column 1: [ 2  6 10]
2D Sub-matrix Slicing:
[[2 3]
 [6 7]]

3D Array Shape: (2, 3, 4), Dimensions (ndim): 3

Reshaped Matrix Shape: (10, 10)
Flattened Array Shape: (100,)


### Task 2: Vectorized Arithmetic & Linear Algebra

In [6]:
X = np.array([[2,3], [1,4]])
Y = np.array([[5,1], [0,2]])

print(f"Addition (X + Y):\n{X + Y}")
print(f"Element-wise Product (X * Y):\n{X * Y}")
print(f"Matrix Multiplication (X @ Y): \n{X @ Y}")

A = np.array([[3,1], [2,4]])
A_transpose = A.T
A_det = np.linalg.det(A)

print(f"\nMatrix A:\n{A}")
print(f"Transpose of A:\n{A_transpose}")
print(f"Determinant of A: {A_det:.2f}")

if A_det != 0:
    A_inv = np.linalg.inv(A)
    print(f"Inverse of A:\n{A_inv}")

    identity_check = A @ A_inv
    is_identity = np.allclose(identity_check, np.eye(2))
    print(f"A @ A^-1 Verification (is Identity? ): {is_identity}")

Addition (X + Y):
[[7 4]
 [1 6]]
Element-wise Product (X * Y):
[[10  3]
 [ 0  8]]
Matrix Multiplication (X @ Y): 
[[10  8]
 [ 5  9]]

Matrix A:
[[3 1]
 [2 4]]
Transpose of A:
[[3 2]
 [1 4]]
Determinant of A: 10.00
Inverse of A:
[[ 0.4 -0.1]
 [-0.2  0.3]]
A @ A^-1 Verification (is Identity? ): True


### Task 3: Normal Distribution and Histogram

In [ ]:
mu_chosen = 50
sigma_chosen = 8 
sample_size = 1000

norm_samples = np.random.normal(loc=mu_chosen, scale=sigma_chosen, size=sample_size)

sample_mean = np.mean(norm_samples)
sample_std = np.std(norm_samples)

print(f"Chosen Mean: {mu_chosen} | Sample Mean: {sample_mean:2f}")
print(f"Chosen Std: {sigma_chosen} | Sample Std: {sample_std:.2f}")

plt.figure(figsize=(8,5))
plt.hist(norm_samples, bins=30, density=True, alpha=0.6, color='g', edgecolor='black')

xmin, xmax = plt.xlim()
x = np.linspace(xmin, xmax, 100)
p = (1/ (sigma_chosen * np.sqrt(2*np.pi))) * np.exp(-0.5 * ((x - mu_chosen) / sigma_chosen) ** 2)

plt.plot(x,p, 'k', linewidth=2, label='Theoretical PDF')
plt.axvline(sample_mean, color='red', linestyle='dashed', linewidth=1.5, label=f'Sample Mean ({sample_mean:.2f})')
plt.title('Normal Distribution Hostogram (N=1000)')
plt.xlabel('Value')
plt.ylabel('Probability Density')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()